# Generated by Django 5.1.1 on 2024-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vl_count', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('attended_last_appointment', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('mh', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('breastfeeding', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('pregnant', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('prediction_text', models.CharField(max_length=255)),
                ('recommendations', models.JSONField(default=list)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
