# Generated by Django 5.1.1 on 2024-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
