# Generated by Django 5.1.1 on 2024-10-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0002_predictionhistory_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='attended_last_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='breastfeeding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mh',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pregnant',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vl_count',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictor.patient'),
        ),
    ]
