# Generated by Django 5.1.1 on 2024-10-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0003_remove_patient_attended_last_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_added',
            new_name='date',
        ),
    ]
