# Generated by Django 5.1.1 on 2024-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0005_rename_date_patient_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_added',
        ),
        migrations.AddField(
            model_name='patient',
            name='new_date_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
