# Generated by Django 5.1.1 on 2024-10-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0006_remove_patient_date_added_patient_new_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='new_date_field',
        ),
    ]
