# Generated by Django 5.1.1 on 2024-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0008_remove_predictionhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
