# Generated by Django 5.1.1 on 2024-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0010_rename_date_patient_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
