# Generated by Django 5.1.1 on 2024-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0011_alter_predictionhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
