# Generated by Django 5.1.1 on 2024-10-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0012_alter_predictionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='date',
        ),
    ]
