# Generated by Django 5.1.1 on 2024-10-03 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0013_remove_predictionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='location',
        ),
        migrations.AddField(
            model_name='patient',
            name='attended_last_appointment',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='breastfeeding',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='mh',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnant',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='vl_count',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='patient',
            field=models.CharField(max_length=255),
        ),
    ]
