# Generated by Django 5.1.1 on 2024-10-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0014_remove_patient_age_remove_patient_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='health_facility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
