# Generated by Django 5.1.1 on 2024-10-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0015_predictionhistory_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='age',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='health_facility',
        ),
    ]
